name: Trigger action on CRON
on: [pull_request]
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/30 * * * *'
jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: run every half an hour
        run: echo "Running every 30 minutes"
